name: Docker Image CI

on: [pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      uses: ./.github/workflows/dockerfile
      run: docker build . --file dockerfile --tag kernelbuilder
    - name: Run the docker image
      uses: ./.github/workflows/master.sh
      run: docker run --rm --name kernelbox -v "$(pwd)"/../..:/home/kewluser/app/kernel kernelbuilder:latest /bin/bash master.sh
